### PR TITLE
Mickyreed

### PR DESCRIPTION
**Pull request by mickyreed**
mickyreed added a plate

### CODE REVIEW

**Comment by mickyreed** [comment]
Did you get all this redone mate?.. the wonderburger stuff.. and how did
you go with other assessments?

**Comment by georgedinn** [comment]
Yeah I got everything done except the final assignment in innovation and waiting for the game stuff to get marked. hbu

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mickyreed** [comment]
Yeah all done. Finished innovation today all the questions and reflection.
And we filmed our presentation yesterday. Game I handed in on Saturday and
mob apps finished this morning at 1am lol I have been on computers all day
and up til 3-4 am for the past week getting stuff done. I need a rest! I am
funny enough still doing stuff on my game ironing out some little bugs and
stuff. No pressure though now just for fun!

**Comment by georgedinn** [comment]
Ah fair I was planning on going through the game aswell and making a bunch of scripts to help me if I end up making more games, just to save time. Random question for the innovation stuff how many reports are there? I thought there was just the feasibility one but dylan was saying there was another

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mickyreed** [comment]
Feasibility is part 2. There was the planning document which was part1 it
was similar to the last one where we write down protocols for team
communication etc. Part 3 was the presentation and we need to do the 15
questions and also the reflection

**Pull request merged**
